services:
  locust:
    build:
      context: ./locust           # Carpeta donde está el Dockerfile.locust
      dockerfile: Dockerfile.locust
    container_name: locust
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=http://fastapi:8081
    networks:
      - taller_locust_mlops_net

networks:
  taller_locust_mlops_net:
    external: true
